### ISSUE TITLE
Typos 

### ISSUE THREAD

**Issue by Steditor** [style-guides/CoffeeScript#1]
"Lines MUST not **m**e longer than 80 characters (counting tabs as 4 spaces)"

"Method chains with more than 2 method calls **must** be wrapped and indented." (and I would vote for "SHOULD", same for "Sub-properties MUST not be wrapped")

**Comment by adius** [comment]
I think the style guide should contain as few SHOULDs as possible.
They introduce ambiguities which is exactly what the styleguide is supposed to reduce in the first place.
If you have a specific case where we should not stick to the styleguide, feel free to open a pull request containing the exception.

**Comment by Steditor** [comment]
The problem with wrapping is: you can't enforce not to wrap sub-property navigation without possibly introducing conflicts with the maximum line-length.

**Comment by adius** [comment]
Yeah it could be mentioned, but I think it's clear that line-length is more important
